---

########################### main master ###############################

# First create token on master
- name: Create join token on main master
  shell: |
    kubeadm token create \
      --ttl 10h \
      --description ansible_join_token_{{lookup('pipe','date +%Y%m%d%H%M%S')}} \
      --print-join-command
  register: kubeadm_token_create_result
