---

########################### main_master ###############################

- name: Apply Nginx Ingress Controller and Service
  shell: |
    kubectl \
      --kubeconfig=/home/{{ k8s_user }}/.kube/config \
      apply -f {{ k8s_ingress_config_path }}/nginx-ingress-controller-{{ item }}.yml
  with_items:
    - "config"
    - "service"
  register: kubectl_output
  until:
    - kubectl_output.stdout.find("unexpected EOF") == -1
  retries: 10
  delay: 3

- name: Kubectl output
  debug:
    msg:
      - "{{ item.stdout_lines }}"
  with_items:
    - "{{ kubectl_output.results }}"
