---

# How it works
#     https://kubernetes.github.io/ingress-nginx/how-it-works/
#     https://github.com/kubernetes/ingress-nginx

# Prometheus / Grafana
#     https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/

# !!! WARNING !!!
#     https://github.com/kubernetes/ingress-nginx/blob/master/docs/deploy/baremetal.md

# Services of type NodePort perform source address translation by default.
# This means the source IP of a HTTP request is always the IP address of the
# Kubernetes node that received the request from the perspective of NGINX.

# The recommended way to preserve the source IP in a NodePort setup is to set
# the value of the externalTrafficPolicy field of the ingress-nginx Service spec
# to Local (example).

# !!! warning This setting effectively drops packets sent to Kubernetes
# nodes which are not running any instance of the NGINX Ingress controller.
# Consider assigning NGINX Pods to specific nodes in order to control on what nodes
# the NGINX Ingress controller should be scheduled or not scheduled.

# NOTE:
# - In this playbook the Deployment gets transformed into a Daemonset.
#   Because of this there is an Nginx pod on every master node and thus
#   the package dropping issue should be resolved.
# - It is important though to make sure that there is a pod running on
#   every master, please make sure this is the case!


# Download and configure ingress controller
- name: Include download and configuration tasks
  include: download-and-configure.yml
  when: inventory_hostname in groups['masters']

# Deploy all manifests
- name: Include deployment tasks
  include: apply-manifests.yml
  when: inventory_hostname == main_master
