- name: Deploying test cafe-app
  debug:
    msg: 
      - "Coffee replicas: {{test_app_coffee_replicas}}"
      - "Tea replicas: {{test_app_tea_replicas}}"


# Configre
# - name: Creating test app directory
#   file:
#     path: "{{test_app_path}}/cafe-app/"
#     state: directory

# - name: Copying app configuration files
#   template:
#     src: "{{item}}.j2"
#     dest: "{{test_app_path}}/cafe-app/{{item}}"
#   with_items:
#    - cafe-app.yml
#    - cafe-ingress.yml


# Apply
- name: Applying app
  k8s:
    state: present
    kubeconfig: "/home/{{k8s_user}}/.kube/config"
    definition: "{{ lookup('template', 'cafe-app.yml.j2') }}"

- name: Applying ingress object for app
  k8s:
    state: present
    kubeconfig: "/home/{{k8s_user}}/.kube/config"
    definition: "{{ lookup('template', 'cafe-ingress.yml.j2') }}"

