---

###################### ALL ######################
- name: Install all Cockpit dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - NetworkManager
    - NetworkManager-libnm
    - glib-networking
    - gnutls
    - gsettings-desktop-schemas
    - json-glib
    - libmodman
    - libndp
    - libnl3
    - libproxy
    - nettle
    - trousers
    - wpa_supplicant

- name: Start & Enable NetworkManager service
  systemd:
    name: NetworkManager
    state: restarted
    enabled: yes

- name: Install Cockpit main components
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - cockpit
    - cockpit-bridge          # bridge server-side component
    - cockpit-system          # interface for configuring and troubleshooting
    - cockpit-ws              # Web Service

- name: Install Cockpit extra packages
  yum:
    name: "{{item}}"
  with_items:
    - cockpit-pcp             # PCP integration
    - cockpit-doc             # deployment and developer guide
    - cockpit-dashboard       # remote servers and dashboard
    - cockpit-packagekit      # user interface for package updates
    - cockpit-storaged        # user interface for storage, using
    - cockpit-networkmanager  # user interface for networking
    - cockpit-kdump           # user interface for kernel crash dumping
    - cockpit-docker          # user interface for Docker containers
    - cockpit-kubernetes      # user interface for Kubernetes cluster

    ##### Extra Possibilities #####

    #   - cockpit-selinux            # SELinux package
    #   - cockpit-machines           # user interface for virtual machines
    #   - cockpit-machines-ovirt
    #   - cockpit-sosreport          # user interface for diagnostic reports
    #   - cockpit-subscriptions      # subscription user interface package
    #   - subscription-manager-cockpit
    #   - cockpit-composer           # for creating custom centos 7 images

- name: Open Cockpit service on Firewalld
  firewalld:
    service: cockpit
    zone: public
    state: enabled
    permanent: yes
    immediate: yes

- name: start cockpit service
  systemd:
    name: cockpit
    state: started

- name: enable cockpit.socket
  systemd:
    name: cockpit.socket
    enabled: yes


###################### All ######################
- name: Configure cockpit.conf
  template:
    src: cockpit.conf.j2
    dest: /etc/cockpit/cockpit.conf
    owner: root
    group: root
    mode: 0644

- name: Join nodes to cockpit dashboard
  template:
    src: cockpit-multiple-server.conf.j2
    dest: /etc/cockpit/machines.d/66-webui-custom.json
    owner: root
    group: root
    mode: 0644

- name: Restart Cockpit service
  systemd:
    state: restarted
    enabled: yes
    name: cockpit.socket
