---

stages:
  - vagrant-validate
  - yaml-check
  - ansible-syntax-check


# Ansible Syntax Check
.playook-syntax-check:
  image: cytopia/ansible:2.8
  stage: ansible-syntax-check
  script:
    - ansible-playbook -i $INVENTORY $PLAYBOOK --syntax-check

full-install:
  extends: .playook-syntax-check
  variables:
    PLAYBOOK: playbook-k8s-all.yml
    INVENTORY: inventories/examples/vagrant-full-install.inv

add-master:
  extends: .playook-syntax-check
  variables:
    PLAYBOOK: playbook-kubeadm-add-new-master.yml
    INVENTORY: inventories/examples/vagrant-add-master.inv

add-worker:
  extends: .playook-syntax-check
  variables:
    PLAYBOOK: playbook-kubeadm-add-new-worker.yml
    INVENTORY: inventories/examples/vagrant-add-worker.inv


# Yaml linting
yamllint:
  image: sdesbure/yamllint:latest
  stage: yaml-check
  script:
    - yamllint .


# Vagrant Validation
# - vagrant validate
# - run bootstrap scripts in container (centos/systemd?)
# - yamllint vangrant servers

vagrantfile:
  image: engineerbetter/vagrant:latest
  stage: vagrant-validate
  script:
    - cd Vagrant
    - cat Vagrantfile
    - vagrant --version
    # - VBoxManage --version
    - vagrant validate -p # --debug
