
###################### All ######################
- hosts: all
  become: yes

  tasks:
    # - name: Create a centos user
    #   user:
    #     name: centos
    #     password: "SHA512"
    #     state: present
    #     shell: /bin/bash 
    #     system: no
    #     createhome: yes
    #     home: /home/centos

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        # - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add users to Docker group
      user:
        name: "{{ item }}"
        groups: "docker,{{ item }}"
        append: yes
      with_items:
        - "jorik"

    - name: Open Kubernetes ports on the firewall
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - "80"
        - "443"
        - "6783"
        - "10250"
        - "10255"
        - "30000-32767"

    - name: Open Flannel ports on the firewall
      firewalld:
        port: "{{ item }}/udp"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - "8472"
        - "8285"

    - name: disable SELinux on reboot
      selinux:
        state: disabled

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: add Kubernetes YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: 
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: install kubelet
      yum:
        name: kubelet # kubelet-1.14.0
        state: present
        update_cache: yes
          
    - name: install kubeadm
      yum:
        name: kubeadm # kubeadm-1.14.0
        state: present
        update_cache: yes

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

###################### Master only ###################### 
- hosts: master
  become: yes

  tasks:
    - name: Open Extra Kubernetes ports on the master node firewall
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - "2379-2380"
        - "6443"
        - "10251"
        - "10252"

    - name: install kubectl
      yum:
        name: kubectl # kubectl-1.14.0
        state: present
        allow_downgrade: yes

    - name: install basic bash completion
      yum: 
        name: bash-completion
        state: present

    - name: "kubectl bash completion: source the completion script in ~/.bashrc file"
      shell: echo 'source <(kubectl completion bash)' >> ~/.bashrc
     
    - name: "kubectl bash completion: add the completion script to /etc/bash_completion.d"
      shell: kubectl completion bash >/etc/bash_completion.d/kubectl

