
- name: Update node hostnames
  hostname:
    name: "{{inventory_hostname}}"
    
- name: Update hostfile with all node ip's
  lineinfile:
    path: /etc/hosts
    line: '{{item.ip}}   {{item.hostname}} {{item.hostname}}.{{item.domain}}'
  with_items:
    - "{{hostfile_entries}}"

- name: Install some handy packages
  yum: 
    name: "{{item}}"
    state: present
  with_items:
   - "{{ extra_handy_packages }}"
