
- name: Update node hostnames
  hostname:
    name: "{{inventory_hostname}}"
    
- name: Update hostfile with all node ip's
  lineinfile:
    path: /etc/hosts
    line: '{{item.ansible_host}}   {{item.inventory_hostname}} {{item.inventory_hostname}}.{{item.domain}}'
  with_items:
    - "{{ hostvars[groups['k8s-nodes']] }}"

- name: Install some handy packages
  yum: 
    name: "{{item}}"
    state: present
  with_items:
   - "{{ extra_handy_packages }}"
