# -*- mode: ruby -*-
# vi: set ft=ruby :

# Makes sure the virtual machines get created one by one
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  # enable .env vars
  config.env.enable

  # Get vars from env vars
  k8s_node_count = ENV['K8S_NODE_COUNT'].to_i
  k8s_node_domain = ENV['K8S_NODE_DOMAIN']
  k8s_node_cpus = ENV['K8S_NODE_CPUS'].to_i
  k8s_node_memory = ENV['K8S_NODE_MEMORY'].to_i

  # Debug
  puts "\nCurrent VM count: #{k8s_node_count} \
        \nResources per VM: \
        \n - CPU: #{k8s_node_cpus} \
        \n - Memory: #{k8s_node_memory} MB\n\n"

  # Kubernetes Nodes
  (1..k8s_node_count).each do |i|
    config.vm.define "k8s-node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "k8s-node-#{i}.#{k8s_node_domain}"
      node.vm.network "private_network", ip: "10.8.8.#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-node-#{i}"
        vb.cpus = k8s_node_cpus
        vb.memory = k8s_node_memory
        vb.customize [
          "modifyvm", :id,
          "--audio", "none",
          "--cpuexecutioncap", "50"
        ]
      end
    end
  end
end