# -*- mode: ruby -*-
# vi: set ft=ruby :


# import server config
require 'yaml'
yaml_config = YAML.load_file('vagrant_servers.yaml')
servers = yaml_config['servers']
debug_mode = yaml_config['debug']

# debug servers
if debug_mode
  puts "\nConfigured servers:\n\n"
  servers.each do |item|
    item.each do |key, value|
      puts key.to_s +  ":" + value.to_s
    end
    puts "\n"
  end
end

# start vagrant config
Vagrant.configure("2") do |config|

  # loop servers in config
  servers.each do |server|
    config.vm.define server['name'] do |node|

      # configure base box
      node.vm.box = server['box']
      node.vm.box_version = server[:box_version]

      # configure hostname & network
      node.vm.hostname = server['name']
      node.vm.network :private_network, ip: server['ip'], netmask: "255.255.255.0"

      # configure virtual machine
      node.vm.provider "virtualbox" do |vb|
        vb.name = server[:name]
        vb.customize ["modifyvm", :id, "--cpus", server['cpus']]
        vb.customize ["modifyvm", :id, "--memory", server['memory']]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        vb.customize ["modifyvm", :id, "--audio", "none"]
        vb.customize ["modifyvm", :id, "--groups", "/kubernetes-cluster"]
      end

      # provision virtual machine
      node.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
