---

- name: Deploying test cafe-app
  debug:
    msg:
      - "Coffee replicas: {{ test_app_coffee_replicas }}"
      - "Tea replicas: {{ test_app_tea_replicas }}"
  when: inventory_hostname == main_master

- name: Creating test app directory
  file:
    path: "{{ test_app_path }}/cafe-app/"
    state: directory
  when: inventory_hostname in groups['masters']

- name: Copying app configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ test_app_path }}/cafe-app/{{ item }}"
  with_items:
    - cafe-app.yml
    - cafe-ingress.yml
  when: inventory_hostname in groups['masters']

- name: Deploy test app
  shell: |
    kubectl \
      --kubeconfig=/home/{{ k8s_user }}/.kube/config \
      apply -f {{ test_app_path }}/cafe-app
  when: inventory_hostname == main_master
  ignore_errors: yes
