---

# Preflight checks / requirements
- name: Include kubernetes preflight check requirement tasks
  include: preflight-reqs.yml


# Install some packages
- name: Install some extra packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-devel
    - python3-pip
    - iproute-tc
    - nfs-utils

- name: Upgrade pip
  shell: "pip3 install --upgrade pip --user {{ k8s_user }}"  # pip3 on CentOS8

- name: Python requirements
  python_requirements_facts:
    dependencies:
      - pyyaml
      - requests
      - openshift


# Configure the k8s users and terminals
- name: Include user and terminal customization tasks
  include: configure-users.yml


# Install k8s packages / tools
- name: Include Kubernetes package installation tasks
  include: install-k8s-packages.yml


# Prepare masters
- name: Include tasks to prepare masters for cluster init
  include: prepare-masters.yml
  when: inventory_hostname in groups['masters']
