---

# Preflight checks / requirements
- name: Include kubernetes preflight check requirement tasks
  include: preflight-reqs.yml


# Install some packages
- name: Install some extra packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-devel
    - python3-pip
    - iproute-tc
    - nfs-utils

- name: Upgrade pip
  shell: "pip3 install --upgrade pip --user {{ k8s_user }}"  # pip3 on CentOS8

- name: Install Python requirements
  pip:
    executable: pip3
    name:
      - pyyaml>=3.11
      - openshift>=0.6
      - requests==2.22.0


# Configure the k8s users and terminals
- name: Include user and terminal customization tasks
  include: configure-users.yml


# Install k8s packages
- name: Include Kubernetes package installation tasks
  include: install-k8s-packages.yml


# Install kubens and kubectx
- name: Inclued installation of kubectx and kubens tools
  include: install-kubectx-kubens.yml
  when: inventory_hostname in groups['masters']


# Prepare masters
- name: Include tasks to prepare masters for cluster init
  include: prepare-masters.yml
  when: inventory_hostname in groups['masters']
