
# nodes extra vars
extra_handy_packages:
  - wget
  - htop
  - nano
  - vim
  - tree
  - git
  - nc
  - jq
  - tcpdump
  - iotop


# k8s vars
k8s_version_major: 1.18.6 # 1.16.4
k8s_loadbalancer_ip: 172.16.88.20
k8s_ha_masters: yes
k8s_pods_scheduled_on_master: yes
k8s_user: k8s
k8s_user_password: $6$O5Or6GyG$rfAnZ84jbEq.WaX9WOFe0GM2Lpqev8v5z/rCXCSPeKnXInLwHJfUCXtq2g/kj/DcecOT6Iy7vPbYmpYOdCck2.
k8s_service_cidr: 10.99.0.0/16 # 10.96.0.0/12
k8s_packages_repository_url: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
k8s_kubectx_repository_url: https://github.com/ahmetb/kubectx
k8s_cadvisor_port: 4194
k8s_api_debug_level: "2"
k8s_kubeadm_config_path: /etc/kubernetes/kubeadm
k8s_kubeadm_apiserver_address: 172.16.88.21 # leave empty for default
k8s_kubeadm_apiserver_port: 6443
k8s_ignore_preflight_errors: no
k8s_pre_pull_images: no

# CNI
k8s_cni_plugin: flannel
k8s_cni_pod_cidr: 10.88.0.0/16 # for now use the same as in the git yaml!!!
k8s_cni_file_url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
k8s_cni_config_path: /etc/kubernetes/cni

# ingress
k8s_ingress_file_url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
k8s_ingress_config_path: /etc/kubernetes/ingress
# k8s_ingress_replicas: 3
k8s_ingress_namespace: ingress-nginx
k8s_ingress_service_type: NodePort
k8s_ingress_nodeport_http: 30080
k8s_ingress_nodeport_https: 30443



# test app
test_app_coffee_replicas: 6
test_app_tea_replicas: 9
test_app_url: test-2.jorsel.be
test_app_path: /DATA

# loadbalancer
lb_ssl_ciphers: EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
lb_galaxy_acl: False
lb_listen_domains:
  - milkywaygalaxy.be
  - jorsel.be
  # - ellievision.be
lb_k8s_api_url: k8s.milkywaygalaxy.be
lb_k8s_api_cert_domain: milkywaygalaxy.be
lb_k8s_api_port: 6443
lb_k8s_public_ip: 172.16.88.20 # 148.251.246.29
# lb_k8s_api_allowd_paths:
  # - /

