---

# openssl genrsa -out ca.key 2048
- name: Generate CA private key
  openssl_privatekey:
    path: "/tmp{{ etcd_certs_directory }}/ca.key"
    type: RSA
    size: 2048

# openssl req -new -key ca.key -subj "/CN=KUBERNETES-CA" -out ca.csr
- name: Generate CA CSR using the CA private key
  openssl_csr:
    path: "/tmp{{ etcd_certs_directory }}/ca.csr"
    privatekey_path: "/tmp{{ etcd_certs_directory }}/ca.key"
    common_name: KUBERNETES-CA

# openssl x509 -req -in ca.csr -signkey ca.key -CAcreateserial -out ca.crt -days 1000
- name: Sign the CSR with the CA private key
  openssl_certificate:
    path: "/tmp{{ etcd_certs_directory }}/ca.crt"
    csr_path: "/tmp{{ etcd_certs_directory }}/ca.csr"
    privatekey_path: "/tmp{{ etcd_certs_directory }}/ca.key"
    provider: selfsigned