---

# Note:
#   openssl has issues with alt names so using shell module instead here with a configfile

# openssl genrsa -out etcd-server.key 2048
- name: Generate etcd private key
  openssl_privatekey:
    path: "/tmp{{ etcd_certs_directory }}/etcd-server.key"
    type: RSA
    size: 2048

- name: Create openssl config file
  template:
    src: openssl-etcd.cnf.j2
    dest: "/tmp{{ etcd_certs_directory }}/openssl-etcd.cnf"

# openssl req -new -key etcd-server.key -subj "/CN=etcd-server" -out etcd-server.csr -config openssl-etcd.cnf
- name: Generate etcd CSR using the etcd private key
  shell: |
    openssl req -new \
      -key /tmp{{ etcd_certs_directory }}/etcd-server.key \
      -subj "/CN=etcd-server" \
      -out /tmp{{ etcd_certs_directory }}/etcd-server.csr \
      -config /tmp{{ etcd_certs_directory }}/openssl-etcd.cnf

# openssl x509 -req -in etcd-server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
#       -out etcd-server.crt -extensions v3_req -extfile openssl-etcd.cnf -days 1000
- name: Sign the CSR with the etcd private key
  shell: |
    openssl x509 -req \
      -in /tmp{{ etcd_certs_directory }}/etcd-server.csr \
      -CA /tmp{{ etcd_certs_directory }}/ca.crt \
      -CAkey /tmp{{ etcd_certs_directory }}/ca.key \
      -CAcreateserial \
      -out /tmp{{ etcd_certs_directory }}/etcd-server.crt \
      -extensions v3_req \
      -extfile /tmp{{ etcd_certs_directory }}/openssl-etcd.cnf \
      -days 1000
