# Replace the CIDR
- name: "Register original Flannel pods CIDR: 10.244.0.0/16"
  set_fact:
    original_flannel_pod_cidr: 10.244.0.0/16

- name: Install Flannel CNI plugin
  become: yes
  become_user: "{{k8s_user}}"
  shell: |
    kubectl apply -f {{k8s_cni_file_url | regex_replace(original_flannel_pod_cidr, k8s_cni_cidr)}} >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: Flannel installed pod CIDR
  debug: 
    msg: "{{k8s_cni_cidr}}"