# Replace the CIDR
- name: "Register original pod cidr"
  set_fact:
    original_flannel_pod_cidr: 10.244.0.0/16

- name: Create CNI config directory
  file:
    path: "/etc/kubernetes/cni"
    state: directory
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    mode: 0555

- name: Download CNI yaml file
  get_url:
    url: "{{k8s_cni_file_url}}"
    dest: "{{k8s_cni_config_path}}/flannel-cni-config.yml"

- name: Replace original pod CIDR with custom pod CIDR in yaml file
  replace:
    path: "{{k8s_cni_config_path}}/flannel-cni-config.yml"
    regexp: "{{original_flannel_pod_cidr}}"
    replace: "{{k8s_cni_pod_cidr}}"

- name: Apply Flannel CNI plugin
  become: yes
  become_user: "{{k8s_user}}"
  shell: |
    kubectl apply -f {{k8s_cni_config_path}}/flannel-cni-config.yml |tee pod_network_setup.txt
  args:
    chdir: "/home/{{k8s_user}}/"
    creates: pod_network_setup.txt
  register: kubectl_output

- name: Kubectl output
  debug:
    msg: 
      - "{{ kubectl_output.stdout_lines }}"

- name: Flannel installed pod CIDR
  debug: 
    msg:
      - "Configured pod CIDR to {{k8s_cni_pod_cidr}} instead of original {{original_flannel_pod_cidr}}"