
# - name: Install jorsel.nginx role
 
- name: Configure Nginx loadbalancer config
  template:
    src: loadbalancer/nginx-confd-k8s-loadbalancer.conf.j2
    dest: /etc/nginx/conf.d/k8s-loadbalancer.conf
    mode: 0644

- name: Configure k8s-api ACL
  template:
    src: loadbalancer/k8s-api.acl.j2
    dest: /etc/nginx/k8s-api.acl
    mode: 0644

- name: Create log directory for each domain
  file:
    state: directory
    path: "/var/log/nginx/{{item}}/"
    mode: 0755
  with_items:
    - "{{lb_listen_domains}}"

- name: Create certificate directory for each domain
  file:
    state: directory
    path: "/DATA/certificates/{{item}}/"
    mode: 0755
  with_items:
    - "{{lb_listen_domains}}"



# - name: Restart Nginx