
# kubeadm token create --ttl 10m --print-join-command
# kubeadm init phase upload-certs --upload-certs

# kubeadm join 192.168.122.170:6443 \
#     --control-plane \
#     --certificate-key 9555b74008f24687eb964bd90a164ecb5760a89481d9c55a77c129b7db438168 \
#     --token xaw58o.0fjg0xp0ohpucwhr \
#     --discovery-token-ca-cert-hash sha256:5efac16c86e5f2ed6b20c6dbcbf3a9daa5bf75aa604097dbf49fdc3d1fd5ff7d




########################### master-initial ###############################

# First create token on initial master
- name: Create join token on initial master
  shell: |
    kubeadm token create \
      --ttl 10m \
      --print-join-command
  register: master_join_command
  when: inventory_hostname in groups['master-initial']

- name: Debug master_join_command
  debug:
    msg: "{{ master_join_command.stdout }}"
  when: inventory_hostname in groups['master-initial']


# Upload certs on initial master
- name: Upload certs on initial master
  shell: |
    kubeadm init phase upload-certs \
      --upload-certs | grep -v upload-certs
  register: master_upload_cert
  when: inventory_hostname in groups['master-initial']
  
- name: Debug master_upload_cert
  debug:
    msg: "{{ master_upload_cert.stdout }}"
  when: inventory_hostname in groups['master-initial']

- name: Register kube config
  shell: |
    cat /home/{{k8s_user}}/.kube/config
  register: kube_config_content
  when: inventory_hostname in groups['master-initial']

- name: Debug kube config
  debug:
    msg: "{{ kube_config_content }}"
  when: inventory_hostname in groups['master-initial']

########################### master-ha ###############################

# Join new HA masters
- name: Create .kube directory
  file:
    path: "/home/{{k8s_user}}/.kube"
    state: directory
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    mode: 0755
  when: inventory_hostname in groups['master-ha']

- name: Join HA masters to the cluster
  shell: |  
    {{master_join_command}} \
      --certificate-key {{master_upload_cert}} \
      --control-plane >> master_node_joined.txt
  args:
    chdir: "/home/{{k8s_user}}/"
    creates: master_node_joined.txt
  when: inventory_hostname in groups['master-ha']

- name: Configure kube config on HA masters
  shell: |
    echo {{kube_config_content.stdout}} > /home/{{k8s_user}}/.kube/config
  when: inventory_hostname in groups['master-ha']


########################### all mastes ###############################

# Get node status
- name: Get node status
  become_user: "{{k8s_user}}"
  shell: |
    kubectl get nodes
  register: get_nodes
  when: inventory_hostname in groups['masters']

- name: Debug get nodes
  debug:
    msg: "{{ get_nodes.stdout_lines }}"
  when: inventory_hostname in groups['masters']