# https://itnext.io/on-premise-ha-kubernetes-cluster-15e41f18bd12
# https://octetz.com/posts/ha-control-plane-k8s-kubeadm


########################### master-initial ###############################

# First create token on initial master
- name: Create join token on initial master
  shell: |
    kubeadm token create \
      --ttl 10m \
      --print-join-command
  register: kubeadm_token_create_result
  when: inventory_hostname in groups['master-initial']


# Upload certs on initial master
- name: Upload certs on initial master
  shell: |
    kubeadm init phase upload-certs \
      --upload-certs | grep -v upload-certs
  register: kubeadm_init_phase_result
  when: inventory_hostname in groups['master-initial']
  

########################### master-ha ###############################

# vars
- name: Register vars on HA masters
  set_fact:
    master_join_command: "{{ hostvars[groups['master-initial'][0]]['kubeadm_token_create_result'].stdout }}"
    master_upload_certs: "{{ hostvars[groups['master-initial'][0]]['kubeadm_init_phase_result'].stdout }}"
  when: inventory_hostname in groups['master-ha']

- name: Debug vars on first HA master
  debug:
    msg:
      - "master_join_command: {{master_join_command}}"
      - "master_upload_certs: {{master_upload_certs}}"
  when: inventory_hostname in groups['master-ha']


# full join command
- name: Register HA master join command
  set_fact:
    full_join_command: |
      {{master_join_command}} \
        --certificate-key {{master_upload_certs}} \
        --control-plane \
        --v={{k8s_api_debug_level}}
  when: inventory_hostname in groups['master-ha']

- name: Debug master join command
  debug:
    msg: "{{full_join_command}}"
  when: inventory_hostname in groups['master-ha']


# join master to cluster
- name: Pull kubeadm images beforehand
  shell: kubeadm config images pull
  when: inventory_hostname in groups['master-ha']

- name: Join HA masters to the cluster
  shell: |
    {{full_join_command}} >> master_node_joined.txt
  args:
    executable: /bin/bash
    chdir: "/home/{{k8s_user}}/"
    creates: master_node_joined.txt
  when: inventory_hostname in groups['master-ha']


# kube config + join
- name: Create .kube directory
  file:
    path: "/home/{{k8s_user}}/.kube"
    state: directory
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    mode: 0755
  when: inventory_hostname in groups['master-ha']

- name: Copy admin.conf to .kube folder
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{k8s_user}}/.kube/config"
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    remote_src: yes
  when: inventory_hostname in groups['master-ha']


########################### all mastes ###############################

# Get node status
- name: Get node status
  become_user: "{{k8s_user}}"
  shell: |
    kubectl get nodes
  register: get_nodes
  when: inventory_hostname in groups['master-initial']

- name: Debug get nodes
  debug:
    msg: "{{ get_nodes.stdout_lines }}"
  when: inventory_hostname in groups['master-initial']
