
########################### master-initial ###############################

# First create token on master
- name: Create join token on master
  shell: |
    kubeadm token create \
      --ttl 10m \
      --print-join-command
  register: kubeadm_token_create_result
  when: inventory_hostname in groups['master-initial']


###################### Workers ######################

# vars
- name: Register vars on workers
  set_fact:
    worker_join_command: "{{ hostvars[groups['master-initial'][0]]['kubeadm_token_create_result'].stdout }}"
  when: inventory_hostname in groups['workers']

- name: Debug worker join command
  debug:
    msg: "worker_join_command: {{worker_join_command}}"
  when: inventory_hostname in groups['workers']


# join worker to cluster  
# if needed (--ignore-preflight-errors all)
- name: Join worker to the cluster
  shell: |
    {{worker_join_command}} >> worker_node_joined.txt
  args:
    executable: /bin/bash
    chdir: "/home/{{k8s_user}}/"
    creates: worker_node_joined.txt
  when: inventory_hostname in groups['workers']


########################### master ###############################

# Get node status
- name: Get node status
  become_user: "{{k8s_user}}"
  shell: kubectl get nodes
  register: get_nodes
  when: inventory_hostname in groups['masters']

- name: Debug get nodes
  debug:
    msg: "{{ get_nodes.stdout_lines }}"
  when: inventory_hostname in groups['masters']
