# labeling for all nodes is done through a master

- name: test ansible_play_hosts
  debug:
    msg: "{{ansible_play_hosts}}"

# Remove old role labels
- name: Remove master & worker labels from all nodes
  become_user: "{{k8s_user}}"
  shell: "kubectl label node {{item.0}} {{item.1}}-"
  with_nested: 
    - "{{ansible_play_hosts}}"
    - [
      "node-role.kubernetes.io/master", 
      "node-role.kubernetes.io/worker"
      ]
  when: inventory_hostname in groups['master-initial']


# Set new role labels
- name: Set master role label on masters
  become_user: "{{k8s_user}}"
  shell: "kubectl label node {{item.0}} {{item.1}}"
  with_nested: 
    - "{{ groups['masters'] }}"
    - node-role.kubernetes.io/master=master
  when: inventory_hostname in groups['master-initial']
  

- name: Set worker role label on workers
  become_user: "{{k8s_user}}"
  shell: "kubectl label node {{item.0}} {{item.1}}"
  with_nested: 
    - "{{groups['workers']}}"
    - node-role.kubernetes.io/worker=worker
  when: inventory_hostname in groups['master-initial']


# Debug current labels
- name: Get all labels on each node
  become_user: "{{k8s_user}}"
  shell: "kubectl get node {{item}} -o custom-columns=LABELHEADER:.metadata.labels | grep -v LABELHEADER"
  with_items: 
    - "{{ansible_play_hosts}}"
  register: node_labels
  when: inventory_hostname in groups['master-initial']

- name: Debug node labels
  debug:
    msg: "{{item.stdout}}"
  with_items:
    - "{{node_labels.results}}"
  when: inventory_hostname in groups['master-initial']


