###################### Master (first in cluster) ######################

- name: Pull kubeadm images beforehand
  shell: kubeadm config images pull


# add
# customg
# config file
# for apiversion: cluster
# https://www.youtube.com/watch?v=27v36t-3afQ&t=151s
# custom pod/bridge network etc etc
# controlpane endpoint to nginx: roundrobin

- name: Create kubeadm config path
  file:
    path: "{{k8s_kubeadm_config_path}}"
    state: directory
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    mode: 0755

- name: Copy custom kubeadm-config.yml
  template:
    src: kubeadm-config.yml.j2
    dest: "{{k8s_kubeadm_config_path}}/kubeadm-config.yml"

# this cidr has to be the same as in the CNI config!! otherwise coredns pods won't start!
- name: Initialize the cluster without HA config
  shell: |
    kubeadm init \
      --pod-network-cidr={{k8s_cni_cidr}} >> cluster_initialized.txt
  args:
    chdir: "/home/{{k8s_user}}/"
    creates: cluster_initialized.txt
  when: not k8s_ha_masters |bool

- name: Initialize the cluster with HA config
  shell: |
    kubeadm init \
      --config={{k8s_kubeadm_config_path}}/kubeadm-config.yml \
      --upload-certs >> cluster_initialized.txt
  args:
    chdir: "/home/{{k8s_user}}/"
    creates: cluster_initialized.txt
  when: k8s_ha_masters |bool

- name: Create .kube directory
  file:
    path: "/home/{{k8s_user}}/.kube"
    state: directory
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    mode: 0755

- name: Copy admin.conf to .kube folder
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{k8s_user}}/.kube/config"
    owner: "{{k8s_user}}"
    group: "{{k8s_user}}"
    remote_src: yes

# - name: Allow running pods on the master node
#   become: yes
#   become_user: "{{k8s_user}}"
#   shell: kubectl taint nodes --all node-role.kubernetes.io/master-
#   when: "{{k8s_pods_scheduled_on_master}}"
