# labeling for all nodes is done through a master

- name: Remove master & worker labels from all nodes
  become_user: "{{k8s_user}}"
  shell: "kubectl label node {{item.0}} {{item.1}}-"
  with_nested: 
    - "{{hostvars}}"
    - [
      "node-role.kubernetes.io/master", 
      "node-role.kubernetes.io/worker"
      ]
  when: inventory_hostname in groups['master-initial']


# - name: Set master label on masters
#   become_user: "{{k8s_user}}"
#   shell: "kubectl label node {{item}} node-role.kubernetes.io/master=master"
#   with_items: 
#     - "{{groups['masters']}}"
#   when: inventory_hostname in groups['master-initial']
  

# - name: Set worker label on masters
#   become_user: "{{k8s_user}}"
#   shell: "kubectl label node {{item}} node-role.kubernetes.io/worker=worker"
#   with_items: 
#     - "{{groups['workers']}}"
#   when: inventory_hostname in groups['master-initial']





# - name: Label workers






# - name: Debug node labels
#   debug:
#     msg:


