
# "Adding workers to the cluster involves executing a single 
# command on each. This command includes the necessary 
# cluster information, such as the IP address and port of 
# the master's API Server, and a secure token. 
# Only nodes that pass in the secure token will be able join 
# the cluster."

###################### Master ######################
- name: Get join command on initial master node
  shell: |
    kubeadm token create \
      --print-join-command
  register: worker_join_command
  when: inventory_hostname in groups['master-initial']

- name: Debug worker join command
  debug:
    msg: "{{worker_join_command}}"



###################### Workers ######################
- name: Join worker into cluster
  shell: |
    {{ worker_join_command }} \
      --ignore-preflight-errors all  >> node_joined.txt
  # shell: "{{ hostvars[groups['master'][0]]['join_command'] }} >> node_joined.txt"
  args:
    chdir: "/home/{{k8s_user}}/"
    creates: worker_node_joined.txt