
# "Adding workers to the cluster involves executing a single 
# command on each. This command includes the necessary 
# cluster information, such as the IP address and port of 
# the master's API Server, and a secure token. 
# Only nodes that pass in the secure token will be able join 
# the cluster."

###################### Master ######################
- name: Get join command on master node
  when: inventory_hostname in groups['masters']
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command from master node
  when: inventory_hostname in groups['masters']
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Debug join command
  debug: 
    var=join_command



###################### Workers ######################
- name: Join worker into cluster
  shell: "{{ hostvars['master'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
  # shell: "{{ hostvars[groups['master'][0]]['join_command'] }} >> node_joined.txt"
  args:
    chdir: "/home/{{k8s_user}}/"
    creates: node_joined.txt