
# Debug
- name: Get node status
  shell: kubectl --kubeconfig=/home/{{k8s_user}}/.kube/config get nodes
  register: get_nodes
  when: inventory_hostname == master_main

- name: Kubernetes installation complete
  debug: 
    msg: 
      - "Kubernetes installation complete"
      - "{{ get_nodes.stdout_lines }}"
  when: inventory_hostname == master_main






# print status messages:
# - docker status/info
# - kubectl
# kubens
# reinit van masters/joins tegengaan van nodes die al gejoined zijn
# enkel joinen als nog geen deel
# k9s