# CNI requires masquerading
- name: Enable IP masquerading
  shell: "firewall-cmd --permanent --add-masquerade"

# All nodes
- name: Open Kubernetes firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 80/tcp
    - 443/tcp
    - 53/tcp
    - 53/udp
    - 6783/tcp
    - 10250/tcp         # Kubelet API
    - 10255/tcp
    - 30000-32767/tcp

# Masters
- name: Open Extra Kubernetes firewalld ports on master nodes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 2379-2380/tcp     # etcd server client API
    - 6443/tcp          # Kubernetes API server
    - 10251/tcp         # kube-scheduler
    - 10252/tcp         # kube-controller-manager
  when: inventory_hostname in groups['masters']

# Flannel CNI
- name: Open Flannel CNI ports on the firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 8472/udp
    - 8285/udp
  when: k8s_cni_plugin |lower == "flannel"

# Reload
- name: Reload firewalld
  shell: firewall-cmd --reload

# Check / Debug
- name: Get firewalld configuration
  shell: |
    firewall-cmd --list-all | egrep -i "interfaces|services| ports|masquerade"
  register: firewalld_output

- name: Debug firewalld configuration
  debug:
    msg:
      - "Node group: {{group_names}}"
      - "{{ firewalld_output.stdout_lines }}"