---

- name: Make sure Firewalld is running for "firewall-cmd" command
  service:
    name: firewalld
    state: started
    enabled: yes

# CNI requires masquerading
- name: Enable IP masquerading
  shell: "firewall-cmd --permanent --add-masquerade"

# This module is required to enable transparent masquerading
# and to facilitate Virtual Extensible LAN (VxLAN) traffic
# for communication between Kubernetes pods across the cluster.
- name: load netfilter probe
  modprobe:
    name: br_netfilter
    state: present

# All nodes
- name: Open common ports on all nodes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ master_node_ports }}"

- name: Open on extra ports on masters
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - "{{ master_node_ports }}"
    - "{{ etcd_ports }}"
  when: inventory_hostname in groups['masters']

# Flannel CNI
- name: Open Flannel CNI ports on the firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ cni_ports_flannel }}"
  when: k8s_cni_plugin |lower == "flannel"

# Reload
- name: Reload firewalld
  shell: firewall-cmd --reload

# Check / Debug
- name: Get firewalld configuration
  shell: |
    firewall-cmd --list-all | egrep -i "interfaces|services| ports|masquerade"
  register: firewalld_output

- name: Debug firewalld configuration
  debug:
    msg:
      - "Node group: {{group_names}}"
      - "{{ firewalld_output.stdout_lines }}"
