- name: Remove all old Docker packages
  yum: 
    name: "{{ docker_remove_packages }}"
    state: removed
  vars:
    docker_remove_packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engi
  when: docker_remove_old_docker_packages |bool

- name: Make sure all required packages are installed
  yum:
    name: "{{ docker_required_packages }}"
    state: present
  vars:
    docker_required_packages:
      - yum-utils
      - bridge-utils
      - device-mapper-persistent-data
      - lvm2

- name: Add Docker repository
  get_url:
    url: "{{docker_repository_url}}"
    dest: /etc/yum.repos.d/docker-ce.repo
    
- name: Install Docker
  yum:
    name: "{{docker_packages}}"
    state: latest
  vars:
    docker_packages:
      - "docker-ce-{{docker_version}}"
      - "docker-ce-cli-{{docker_version}}"

- name: "Installed Docker version:"
  debug:
    msg: "{{docker_version}}"

# kubernetes docker config driver=systemd
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Create docker config directory for daemon.json
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Copy daemon.json template
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  
- name: Start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes