---

- name: Remove all old Docker packages
  yum:
    name: "{{ item }}"
    state: removed
  with_items: "{{ docker_packages_to_remove }}"
  when: docker_remove_old_docker_packages |bool

- name: Make sure all required packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_required_packages }}"

- name: Add Docker repository
  get_url:
    url: "{{docker_repository_url}}"
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install containerd
  yum:
    name: "{{ docker_containerd_rpm_package_url }}"
    state: present

- name: Install Docker
  yum:
    name: "{{item}}"
    state: latest
  with_items: "{{docker_packages}}"

- name: "Installed Docker version:"
  debug:
    msg: "{{docker_version}}"

# kubernetes docker config driver=systemd
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Create docker config directory for daemon.json
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Copy daemon.json template
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
