
############################ kubernetes ################################

# # Debug
# - name: Starting Kubernetes installation
#   debug: 
#     msg: "{{group_names}}"
#   when: inventory_hostname in groups['k8s-nodes']



# Loadbalancer 
- name: Setup Nginx Loadbalancer VM
  include: install_loadbalancer.yml
  when: 
    - install_loadbalancer |bool
    - inventory_hostname in groups['loadbalancer']



# Ingress 
- name: Include Nginx ingress tasks
  include: nginx_ingress.yml
  when: 
    - inventory_hostname in groups['masters']
    - install_nginx_ingress |bool


# Debug
- name: Get node status
  become_user: "{{k8s_user}}"
  shell: kubectl get nodes
  register: get_nodes
  when: inventory_hostname in groups['master-initial']

- name: Kubernetes installation complete
  debug: 
    msg: 
      - "Kubernetes installation complete"
      - "{{ get_nodes.stdout_lines }}"
  when: inventory_hostname in groups['master-initial']






# print status messages:
# - docker status/info
# - kubectl
# kubens
# reinit van masters/joins tegengaan van nodes die al gejoined zijn
# enkel joinen als nog geen deel
# k9s