- hosts: k8s-nodes
  tasks:
    - name: "Starting full Kubernetes cluster installation on nodes:"
      debug:
        msg: 
          - "Nodes: {{ groups['k8s-nodes'] }}"
          - "Masters: "
          - "Workers: {{ groups['workers'] }}"
          - "Main-Master: {{ groups['masters'] }}[0]"
      when: "inventory_hostname == groups['masters'][0]"
    
    - name: "Register main master that will be used to get all the data from"
      set_fact:
        main_master: "{{ groups['masters'][0] }}"

    - name: "Ready to start importing other playbooks"
      debug: 
        msg: "main-master: {{main_master}}"
      when: "inventory_hostname == main_master"

# - { import_playbook: cleanup-vms,  when: reinit_vms_completely |bool }
# - import_playbook: nginx-k8s-lb.yml

- import_playbook: prep-node-vms.yml
# - import_playbook: ntpd.yml   BROKEN on sync time
- import_playbook: docker.yml
- import_playbook: firewalld.yml
- import_playbook: k8s-dependencies.yml
- import_playbook: k8s-init-masters.yml
- import_playbook: k8s-init-workers.yml
- import_playbook: k8s-label-nodes.yml
- { import_playbook: nginx-ingress-controller.yml, when: "inventory_hostname in groups['masters']" }
- import_playbook: cockpit.yml
- import_playbook: k8s-cluster-info.yml

# test
- { import_playbook: test-run.yml, when: deploy_test_app |bool }
